#!/bin/bash

 cp -rfp util/hooks/* .git/hooks
 chmod +x util/hook.sh
 
 mtimestore -r

 #git update-index --refresh #causes some problems under windows tortoise git
 
 git log  -n 10 > version-last10.txt
