#!/bin/bash

  cat .mtimes |  ruby util/mtimeh.rb  > mtimeh.txt
  sort -r mtimeh.txt   > mtimehs.txt
    sleep 1

  # git add .mtimes mtimeh.txt mtimehs.txt

  cp -rfp util/hooks/* .git/hooks

  git log  -n 10 > version__may-be-missing-one-version.txt

  util/version.sh
  
  mtimestore -s
  sleep 2
  git add -A