#!/bin/bash

  mtimestore -s
    sleep 2

  cat .mtimes |  ruby util/mtimeh.rb  > mtimeh.txt
  sort -r mtimeh.txt   > mtimehs.txt
    sleep 1

  git add .mtimes mtimeh.txt mtimehs.txt

  cp -rfp util/hooks/* .git/hooks
 